export enum IpcChannel {
  BondRequested = 'bond-requested',
  BluetoothDeviceFound = 'bluetooth-device-found',
  StateBluetoothScan = 'state-bluetooth-scan',
  StateSyncRequestListen = 'state-sync-request-listen',
  StartBluetoothScan = 'start-bluetooth-scan',
  RequestSync = 'request-sync',
  RespondToBondRequest = 'respond-to-bond-request',
  ListenSyncRequest = 'listen-sync-request',
  DisableSync = 'disable-sync',
  GetSyncDevices = 'get-sync-devices',

  GetAllThreads = 'get-all-threads',
  CreateThread = 'create-thread',
  UpdateThread = 'update-thread',
  RemoveThread = 'remove-thread',
  DeleteThread = 'delete-thread',

  GetAllNotes = 'get-all-notes',
  GetNotes = 'get-notes',
  GetTree = 'get-Tree',
  SearchNote = 'search-note',
  CreateNote = 'create-note',
  UpdateNote = 'update-note',
  RemoveNote = 'remove-note',
  RestoreNote = 'restore-note',
  DeleteNote = 'delete-note',
}
